/**
 * wg-distil.mjs — turn the 773KB workgraph index into ONE dated channel entry.
 * Meridian is surface #3 of four; its question is "what is owed TODAY".
 * So we distil to exactly that: the ready frontier, work owed outward, and aging parked.
 */
import fs from 'node:fs';

const IDX = process.argv[2];
const DATE = process.argv[3];
const OUT = process.argv[4];

const ix = JSON.parse(fs.readFileSync(IDX, 'utf8'));
const now = Date.now();
const DAY = 864e5;
const ageOf = (n) => (n.lastTouched ? Math.round((now - Date.parse(n.lastTouched)) / DAY) : null);
const byId = new Map(ix.nodes.map((n) => [n.id, n]));

// story -> its blockers (edge kind 'awaits' points blocker -> blocked)
const blockers = new Map();
for (const e of ix.edges) {
  if (e.kind !== 'awaits') continue;
  if (!blockers.has(e.to)) blockers.set(e.to, []);
  blockers.get(e.to).push(e.from);
}
const isDone = (id) => byId.get(id)?.status === 'done';

// ---- 1. READY FRONTIER: pending, every blocker satisfied ----
const ready = ix.nodes
  .filter((n) => n.kind === 'story' && n.status === 'pending')
  .filter((n) => (blockers.get(n.id) ?? []).every(isDone))
  .sort((a, b) => (a.priority ?? 99) - (b.priority ?? 99) || String(a.epic).localeCompare(String(b.epic)))
  .map((n) => ({
    t: n.title, epic: n.epic, origin: n.origin, pri: n.priority,
    state: 'open', dir: n.direction, age: ageOf(n),
    files: (n.files || []).length,
  }));

// ---- 2. OWED OUTWARD: direction outbound, >14d untouched (the aging policy) ----
const owed = ix.nodes
  .filter((n) => n.direction === 'outbound' && (ageOf(n) ?? 0) > 14)
  .sort((a, b) => (ageOf(b) ?? 0) - (ageOf(a) ?? 0))
  .map((n) => ({
    t: n.title, to: (n.destination || []).join(', '), origin: n.origin,
    state: n.state, dir: 'outbound', age: ageOf(n), summary: n.summary || '',
  }));

// ---- 3. PARKED, AGING: parked >28d (the resurface trigger) ----
const parked = ix.nodes
  .filter((n) => n.state === 'parked' && n.kind === 'worklane' && (ageOf(n) ?? 0) > 28)
  .sort((a, b) => (ageOf(b) ?? 0) - (ageOf(a) ?? 0))
  .map((n) => ({
    t: n.title, summary: n.summary || '', origin: n.origin, session: n.session,
    state: 'parked', dir: n.direction, age: ageOf(n), revisit: n.revisit || '',
  }));

// ---- 4. BLOCKED: pending with an unsatisfied blocker ----
const blocked = ix.nodes
  .filter((n) => n.kind === 'story' && n.status === 'pending')
  .filter((n) => (blockers.get(n.id) ?? []).some((b) => !isDone(b)))
  .map((n) => ({
    t: n.title, epic: n.epic, origin: n.origin,
    on: (blockers.get(n.id) ?? []).filter((b) => !isDone(b)).map((b) => byId.get(b)?.title || b).slice(0, 3),
    state: 'parked', dir: 'local', age: ageOf(n),
  }));

const CAP = 40;
const entry = {
  date: DATE,
  weekday: new Date(DATE + 'T12:00:00').toLocaleDateString('en-US', { weekday: 'long' }),
  kind: 'workgraph',
  summary: 'What is owed today — a read of the one record set. Meridian is surface 3 of 4 (Prism session rail · DGS Workgraph tab · Meridian daily · Djeli).',
  stats: {
    nodes: ix.nodes.length, edges: ix.edges.length,
    generated: ix.generated,
    cycles: (ix.stats?.cycles || []).length,
    byKind: ix.stats?.byKind || {},
    byState: ix.stats?.byState || {},
    byDirection: ix.stats?.byDirection || {},
    sources: ix.stats?.sources || {},
  },
  ready: ready.slice(0, CAP), readyTotal: ready.length,
  owed: owed.slice(0, CAP), owedTotal: owed.length,
  parked: parked.slice(0, CAP), parkedTotal: parked.length,
  blocked: blocked.slice(0, CAP), blockedTotal: blocked.length,
  notes: 'Generated by scripts/workgraph-index.mjs then distilled — never hand-maintained. State decides the lane (border); direction is the badge. Aging thresholds from the ICM grounding design: outbound resurfaces at ~2 weeks, parked at ~4 weeks, adjacent and resolved never. Lists capped at ' + CAP + ' rows; totals are exact.',
};

fs.writeFileSync(OUT, JSON.stringify(entry, null, 1), 'utf8');
console.log(JSON.stringify({
  ok: true, ready: ready.length, owed: owed.length, parked: parked.length, blocked: blocked.length,
  bytes: fs.statSync(OUT).size,
}));
